"""Pydantic I/O contracts for every module seam in the pipeline.

These models ARE the module boundaries. Field names for the working JSON record are
fixed by the record schema. Changing a model here means the corresponding module
specs must be updated to match.

Invariant philosophy: cheap structural checks (bounds, ordering, enum membership,
exactly-one-authoritative) live here as validators and fail at construction time.
Deep invariants that need the canonical stream (slice identity, substring
verification) live in the owning module and its tests - a contract model never
holds enough context to prove them alone.
"""

from __future__ import annotations

import re
import unicodedata
from datetime import date, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

# ---------------------------------------------------------------------------
# Closed vocabularies
# ---------------------------------------------------------------------------

# Economy codes are ISO 3166-1 alpha-2, uppercase. The SET of Economies is DATA
# (config/portals.yaml), not a Literal: adding an Economy must never be a
# contract edit. The shape is checked here; MEMBERSHIP of the configured
# registry is checked at the boundaries that know which registry is loaded
# (the CLI's choices, the server's request validation, the export's portal
# lookup), so a test fixture can carry a code this checkout does not ship.
ECONOMY_CODE_PATTERN = r"^[A-Z]{2}$"
EconomyCode = Annotated[str, Field(pattern=ECONOMY_CODE_PATTERN)]

# Canonical NUMERIC indicator IDs; ALL internal logic uses these. The ID is
# always TEXT: three of them are three-level (12.4.1) and two carry a leading
# zero (4.01, 12.01), so a float would destroy them. The SET of Indicators is
# data too (config/indicators.json, generated by scripts/make_indicators.py
# from the organizer's own sheets); only the shape lives here. Emission format
# (numeric default, P-code alternative) is driven solely by
# indicator_id_crosswalk config.
INDICATOR_ID_PATTERN = r"^\d{1,2}(\.\d{1,2}){1,2}$"
IndicatorId = Annotated[str, Field(pattern=INDICATOR_ID_PATTERN)]

# Exactly NEW or KNOWN, case-sensitive, PROVISION-level.
DiscoveryTag = Literal["NEW", "KNOWN"]

# passed only after BOTH the byte-for-byte substring check and the subsection
# regex check pass; dropped after retries exhaust.
VerificationStatus = Literal["unverified", "passed", "dropped"]

# uncertainty_flags vocabulary, verbatim.
UncertaintyFlag = Literal[
    "missing-information",
    "contradictory-sources",
    "possible-amendment-or-repeal",
    "no-clear-translation-equivalent",
]

# M8 relationship vocabulary.
RelationshipToGroup = Literal[
    "sole_source", "complementary", "superseded_by", "supersedes", "conflicting"
]

# Where the novelty sits for a NEW tag; novelty is assessed at provision level.
NoveltyScope = Literal["law", "provision"]

# M4 chunk accounting: every char of the stream is a section or explicitly
# labelled non-section material.
ChunkKind = Literal["section", "front_matter", "toc", "schedule", "other"]

ReviewStatus = Literal["accepted", "rejected", "flagged", "corrected"]


class _Contract(BaseModel):
    """extra='forbid' so schema drift fails loudly at the seam, not downstream."""

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# M1/M2 - canonical text
# ---------------------------------------------------------------------------


class PageSpan(_Contract):
    """Character range of one page within CanonicalText.full_text."""

    page_number: int = Field(ge=1)
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)

    @model_validator(mode="after")
    def _ordered(self) -> "PageSpan":
        if self.char_end < self.char_start:
            raise ValueError("char_end < char_start")
        return self


class WordBox(_Contract):
    """One word with page coordinates, for the PDF.js highlight overlay (U0)."""

    text: str
    page: int = Field(ge=1)
    x0: float
    y0: float
    x1: float
    y1: float
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)

    @model_validator(mode="after")
    def _ordered(self) -> "WordBox":
        if self.char_end < self.char_start:
            raise ValueError("char_end < char_start")
        return self


class OcrQuality(_Contract):
    """Per-document OCR quality proxies (M2). CER gate is < 0.05.

    ocr_quality_cer holds a MEASURED character error rate when a hand-checked
    reference exists (test/eval runs); cer_proxy_flag is the production stand-in
    (confidence + dictionary proxies below threshold = suspected CER >= 5%)."""

    mean_word_confidence: float = Field(ge=0.0, le=1.0)
    # None when the proxy does not apply: it counts hits against an ENGLISH
    # legal wordlist, so on a Lao or Thai stream it would read 0.0 and be taken
    # for catastrophic OCR. dictionary_hit_rate_note carries the reason.
    dictionary_hit_rate: float | None = Field(default=None, ge=0.0, le=1.0)
    dictionary_hit_rate_note: str | None = None
    # Why manual_review was forced regardless of the measured proxies (a
    # Language with no vendored traineddata was read as English).
    manual_review_reason: str | None = None
    ocr_quality_cer: float | None = Field(default=None, ge=0.0, le=1.0)
    cer_proxy_flag: bool = False
    escalated_to_rapidocr: bool = False
    manual_review: bool = False


class CanonicalText(_Contract):
    """THE canonical stream for one document, produced exactly once (M1 or M2).

    Everything downstream slices full_text by character offsets; nothing may
    re-flow, re-wrap, or clean it up. The verbatim substring check (M7) runs
    against this same stream.
    """

    document_id: str
    source_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    extractor: str  # e.g. "pdfplumber"
    extractor_version: str  # pinned; part of the ground-truth definition
    full_text: str
    pages: list[PageSpan] = Field(default_factory=list)
    words: list[WordBox] = Field(default_factory=list)
    language: str | None = None  # ISO 639-1 where known; None = undetermined
    low_yield_pages: list[int] = Field(default_factory=list)  # < 50 chars -> OCR flag
    ocr_applied: bool = False
    ocr_quality: OcrQuality | None = None

    @model_validator(mode="after")
    def _composed(self) -> "CanonicalText":
        """The stream in one Unicode form (NFC), made here so that every
        producer (text layer, HTML, OCR, a stored stream read back) yields it.
        Already-composed text, which is nearly all of it, passes untouched."""
        from .textnorm import ComposedText, is_nfc

        if is_nfc(self.full_text) and all(is_nfc(w.text) for w in self.words):
            return self
        composed = ComposedText(self.full_text)
        self.full_text = composed.text
        self.pages = [
            p.model_copy(update={
                "char_start": composed.start(p.char_start),
                "char_end": composed.end(p.char_end),
            })
            for p in self.pages
        ]
        self.words = [
            w.model_copy(update={
                "text": unicodedata.normalize("NFC", w.text),
                "char_start": composed.start(w.char_start),
                "char_end": composed.end(w.char_end),
            })
            for w in self.words
        ]
        return self

    @model_validator(mode="after")
    def _spans_in_bounds(self) -> "CanonicalText":
        n = len(self.full_text)
        for p in self.pages:
            if p.char_end > n:
                raise ValueError(f"page {p.page_number} char_end {p.char_end} > stream length {n}")
        for w in self.words:
            if w.char_end > n:
                raise ValueError(f"word at {w.char_start} char_end {w.char_end} > stream length {n}")
        return self

    def slice(self, char_start: int, char_end: int) -> str:
        """The ONLY sanctioned way to obtain text from the stream."""
        return self.full_text[char_start:char_end]


# ---------------------------------------------------------------------------
# M3 - translation gloss (separate from the verbatim stream, always)
# ---------------------------------------------------------------------------


class TranslationGloss(_Contract):
    """English gloss of non-English text. NEVER replaces the verbatim stream.

    Non-authoritative and AI-generated by definition; the flags
    are frozen True so no code path can launder a gloss into evidence.
    """

    source_text: str  # the verbatim source-language text this glosses
    gloss_en: str
    engine: str  # e.g. "opus-mt-mul-en-ct2-int8"
    non_authoritative: Literal[True] = True
    ai_generated: Literal[True] = True


# ---------------------------------------------------------------------------
# M4 - chunks (offset slices, never re-emitted text)
# ---------------------------------------------------------------------------


class Chunk(_Contract):
    """A section-level slice of the canonical stream.

    text MUST equal full_text[char_start:char_end]; construct via from_stream()
    so the slice identity holds by construction. M4's exit test re-proves it.
    """

    chunk_id: str
    document_id: str
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)
    text: str
    section_label: str  # e.g. 's. 16', 'Part IVA s. 26(2)', 'front matter'
    chunk_kind: ChunkKind = "section"
    page_start: int | None = Field(default=None, ge=1)
    page_end: int | None = Field(default=None, ge=1)

    @model_validator(mode="after")
    def _slice_consistent(self) -> "Chunk":
        if self.char_end < self.char_start:
            raise ValueError("char_end < char_start")
        if len(self.text) != self.char_end - self.char_start:
            raise ValueError(
                f"text length {len(self.text)} != span {self.char_end - self.char_start}: "
                "chunk text must be a slice of the canonical stream, never re-emitted"
            )
        return self

    @classmethod
    def from_stream(
        cls,
        canonical: CanonicalText,
        chunk_id: str,
        char_start: int,
        char_end: int,
        section_label: str,
        chunk_kind: ChunkKind = "section",
        page_start: int | None = None,
        page_end: int | None = None,
    ) -> "Chunk":
        return cls(
            chunk_id=chunk_id,
            document_id=canonical.document_id,
            char_start=char_start,
            char_end=char_end,
            text=canonical.slice(char_start, char_end),
            section_label=section_label,
            chunk_kind=chunk_kind,
            page_start=page_start,
            page_end=page_end,
        )


class BoundaryProposal(_Contract):
    """What the LLM boundary fallback (M4) is allowed to return: positions and
    labels ONLY. Any text it emits is discarded unread by contract."""

    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)
    section_label: str
    chunk_kind: ChunkKind = "section"


# ---------------------------------------------------------------------------
# M5 - gate
# ---------------------------------------------------------------------------


class GatedChunk(_Contract):
    """One chunk scored against one indicator. Excluded chunks are logged with
    gate_decision='excluded', never silently dropped."""

    chunk: Chunk
    indicator_id: IndicatorId
    cosine_pillar: float = Field(ge=-1.0, le=1.0)
    bm25_indicator: float = Field(ge=0.0)
    gate_decision: Literal["passed", "excluded"]


# ---------------------------------------------------------------------------
# M6/M7/M8 - mapping records (record schema field list, exactly)
# ---------------------------------------------------------------------------


class Timeline(_Contract):
    """4-part timeline where available."""

    adopted: str | None = None
    entry_into_force: str | None = None
    last_amended: str | None = None
    repeal_status: str | None = None


class MappingRecord(_Contract):
    """One provision-to-indicator mapping (one row of the submission file).

    Field names and vocabulary follow the record schema. confidence is a mechanical
    composite computed by our code - there is deliberately no field
    where the model could self-report one.
    """

    mapping_id: str
    document_id: str
    chunk_id: str
    economy: EconomyCode
    indicator_id: IndicatorId
    indicator_name: str
    section: str
    subsection: str | None = None
    verbatim_quote: str
    page_number: int | None = Field(default=None, ge=1)
    impact: str | None = None
    rdtii_score_contribution: float | None = Field(default=None, ge=0.0, le=1.0)
    insufficient_evidence: bool = False
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    verification_status: VerificationStatus = "unverified"
    discovery_tag: DiscoveryTag | None = None
    measure_type: str | None = None
    timeline: Timeline = Field(default_factory=Timeline)
    source_archived_url: str | None = None
    source_access_date: str | None = None  # ISO date the source was retrieved
    uncertainty_flags: list[UncertaintyFlag] = Field(default_factory=list)
    controlling_evidence: bool | None = None  # filled by M8, exactly one True per group
    novelty_scope: NoveltyScope | None = None
    relationship_to_group: RelationshipToGroup | None = None  # filled by M8
    extraction_attempts: int = Field(default=1, ge=1, le=3)  # 1 initial + max 2 stricter retries

    @model_validator(mode="after")
    def _evidence_rules(self) -> "MappingRecord":
        if self.insufficient_evidence and self.verification_status == "passed":
            raise ValueError("insufficient_evidence records can never be 'passed'")
        if not self.insufficient_evidence and not self.verbatim_quote:
            raise ValueError("a substantive mapping requires a verbatim_quote")
        return self


class DocumentMapping(_Contract):
    """The working JSON record for one document (schema top level):
    mapping_<economy>_<law>_<pillar>.json."""

    economy: EconomyCode
    law_name: str  # full official name + year, no abbreviations
    law_number_ref: str | None = None
    last_amended: str | None = None
    document_id: str
    source_url: str
    mappings: list[MappingRecord] = Field(default_factory=list)


class ReconciledGroup(_Contract):
    """M8 output for one (economy, indicator) group: exactly one authoritative
    mapping (the controlling evidence); losers stay recorded, never dropped."""

    group_id: str
    economy: EconomyCode
    indicator_id: IndicatorId
    mapping_ids: list[str] = Field(min_length=1)
    authoritative_mapping_id: str
    relationships: dict[str, RelationshipToGroup] = Field(default_factory=dict)
    reconciliation_notes: str | None = None

    @model_validator(mode="after")
    def _exactly_one_authoritative(self) -> "ReconciledGroup":
        if self.authoritative_mapping_id not in self.mapping_ids:
            raise ValueError("authoritative_mapping_id must be a member of mapping_ids")
        if len(set(self.mapping_ids)) != len(self.mapping_ids):
            raise ValueError("duplicate mapping_ids in group")
        unknown = set(self.relationships) - set(self.mapping_ids)
        if unknown:
            raise ValueError(f"relationships reference unknown mapping_ids: {sorted(unknown)}")
        return self


# ---------------------------------------------------------------------------
# Zone 1 - crawl + shortlist
# ---------------------------------------------------------------------------


class CrawlManifestEntry(_Contract):
    """One URL's row in the crawl manifest (M10), the checkpoint/resume source
    of truth. The stored bytes are the exact server response body; sha256 is
    computed over those bytes and doubles as the dedupe key. A URL whose bytes
    already exist on disk is still status='fetched' with is_duplicate_of set
    and local_path pointing at the single stored copy."""

    url: str
    economy: EconomyCode
    kind: Literal["document", "index"] = "document"
    source_family: str | None = None
    filename_hint: str | None = None
    status: Literal["pending", "fetched", "failed"] = "pending"
    http_status: int | None = None
    method: str | None = None  # httpx | curl_cffi | playwright
    sha256: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    content_type: str | None = None
    size_bytes: int | None = Field(default=None, ge=0)
    local_path: str | None = None
    is_duplicate_of: str | None = None
    attempts: int = Field(default=0, ge=0)
    error: str | None = None
    fetched_at: datetime | None = None

    @model_validator(mode="after")
    def _fetched_has_bytes(self) -> "CrawlManifestEntry":
        if self.status == "fetched" and (self.sha256 is None or self.local_path is None):
            raise ValueError("a fetched entry must carry sha256 and local_path")
        if self.status == "fetched" and self.fetched_at is None:
            raise ValueError("a fetched entry must carry fetched_at")
        return self


class CrawlTarget(_Contract):
    """One document URL the discovery step resolved from a seed family.
    Seeding is by SOURCE FAMILIES (data protection, telecom, cybersecurity),
    never by feeding indicator questions to a search engine."""

    url: str
    economy: EconomyCode
    source_family: str
    kind: Literal["document", "index"] = "document"
    filename_hint: str | None = None
    # The Portal's own name for the instrument, where its listing gives one
    # (the Lao grid's title, the Register's name). It becomes the Corpus row's
    # title; the id is still read from filename_hint, so no id changes.
    title: str | None = None
    # A secondary reference the Portal published beside this Document, carried
    # to the manifest row and stored on the Corpus row: the Lao Official
    # Gazette offers an English rendering of a few instruments, and its URL is
    # worth recording precisely because it is NEVER the text a verbatim quote
    # is taken from.
    notes: str | None = None


class ShortlistRow(_Contract):
    """One row of the Zone 1 ranked CSV (exact column set)."""

    rank: int = Field(ge=1)
    document_id: str
    title: str
    source_url: str
    relevance_score: float = Field(ge=0.0, le=1.0)
    matched_keywords: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Review + observability
# ---------------------------------------------------------------------------


class Review(_Contract):
    """A Review Decision: one reviewer's accept, reject, flag or correction on
    one Mapping of one Run, with an optional note. Only accepted and corrected
    Mappings enter the Evidence Export, a corrected one under the reviewer's
    Indicator. (run_id, mapping_id) identifies it: a later decision on
    the same Mapping replaces this one rather than queueing behind it.

    A correction names the Indicator the reviewer says the Mapping belongs
    under, and its note is the required reason. The Mapping itself keeps the
    Engine's Indicator: the correction is an override, never an overwrite."""

    review_id: str
    run_id: str
    mapping_id: str
    review_status: ReviewStatus
    reviewer: str | None = None
    reviewed_at: datetime
    comment: str | None = None  # the reviewer's note
    corrected_indicator_id: str | None = None  # a correction's Indicator, else None


class StageLogEntry(_Contract):
    """One audit_log row: every pipeline stage logs exactly this (project audit contract)."""

    stage: str
    input_hash: str | None
    output_hash: str | None
    method: str
    decision: str
    duration_ms: float = Field(ge=0.0)
    timestamp: datetime


# ---------------------------------------------------------------------------
# Config models (loaded from config/*.yaml|json at startup)
# ---------------------------------------------------------------------------


# The organizer's Language dropdown, verbatim (OUTPUT_TEMPLATE_FINAL_ROUND.xlsx,
# Output Data sheet, data validation on N9:N109). Every Document's Language of
# Source must be one of these; anything else, Malay and Portuguese included, is
# "Other".
ORGANIZER_LANGUAGES: tuple[str, ...] = (
    "English",
    "Thai",
    "Vietnamese",
    "Bahasa Indonesia",
    "Chinese",
    "Hindi",
    "Kazakh",
    "Russian",
    "Lao",
    "Mongolian",
    "Other",
)

# Spellings a Document's recorded Language may carry that are not the
# organizer's own word for it. Everything absent from this table AND from
# ORGANIZER_LANGUAGES is "Other": Malay, Portuguese, Tetum and Khmer have no
# organizer value, so naming them would be inventing a dropdown entry.
LANGUAGE_ALIASES: dict[str, str] = {
    "indonesian": "Bahasa Indonesia",
    "bahasa": "Bahasa Indonesia",
    "bahasa indonesian": "Bahasa Indonesia",
    "mandarin": "Chinese",
    "chinese (simplified)": "Chinese",
    "simplified chinese": "Chinese",
    "viet": "Vietnamese",
    "tiếng việt": "Vietnamese",
    "laotian": "Lao",
    "kazakhstani": "Kazakh",
    "mongol": "Mongolian",
    "english (translation)": "English",
}


def organizer_language(raw: str | None) -> str:
    """The Language of Source value the organizer's workbook accepts, for a
    Document whose recorded Language is `raw`.

    The dropdown on Output Data N9:N109 has eleven values and is advisory only,
    so nothing but this function stops an out-of-list word reaching the file
    the secretariat scores criterion C1c from. A Language we cannot place -
    Malay, Portuguese, Tetum, or none recorded at all - is "Other", never a
    guess at the nearest entry."""
    if not raw:
        return "Other"
    cleaned = raw.strip()
    for value in ORGANIZER_LANGUAGES:
        if cleaned.casefold() == value.casefold():
            return value
    return LANGUAGE_ALIASES.get(cleaned.casefold(), "Other")


# The Discovery strategy that fetches nothing. An Economy on this strategy is
# reviewed from Documents added by hand, so it is the one case where the host
# whitelist may be empty.
MANUAL_STRATEGY = "manual"

# Every Discovery strategy name a Portal may name. The VOCABULARY lives here,
# on the base tier, because PortalConfig must validate it and config loading
# must work without the live extra installed; crawl.STRATEGIES binds each name
# to the function that implements it and a test asserts the two agree. Adding
# an Economy that reuses an existing strategy is a portals.yaml edit alone;
# adding a strategy is one entry here and one in crawl.STRATEGIES.
STRATEGY_NAMES: tuple[str, ...] = (
    "playwright",
    "curl_cffi_ladder",
    "httpx",
    "dspace_rest",
    MANUAL_STRATEGY,
)


# What a Portal's configuration may say an UNAVAILABLE robots.txt (a 5xx)
# means for that Portal. `refuse` is RFC 9309's own reading and the default
# everywhere: the rules may exist and the Portal cannot show them, so nothing
# is requested. `proceed` is an operator's explicit decision, recorded per
# Portal with its reason, that this Portal's silence is read as publishing no
# rules; every other politeness rule (the spacing floor, the host whitelist,
# the identified agent, the published rules whenever the Portal CAN serve
# them) is untouched, and every record says which policy let the request out.
ROBOTS_UNAVAILABLE_POLICIES: tuple[str, ...] = ("refuse", "proceed")

# How many connections a Discovery opens to one Portal at a time. The crawler
# caps its single pooled client at this (crawl.one_connection), and the Settings
# screen reads the same name, so the screen cannot disagree with the behaviour.
CONNECTIONS_PER_HOST = 1

# RFC 9309 section 2.3.1.4: a robots.txt that has stayed unavailable (5xx) for
# this many days, counted from the Portal's recorded robots_unreachable_since
# date, may be treated as publishing no rules (crawl.ROBOTS_UNREACHABLE_GRACE).
ROBOTS_UNREACHABLE_GRACE_DAYS = 30


class PortalConfig(_Contract):
    """One Economy's official Portal: host whitelist, Discovery strategy, the
    Coverage Matrix spelling the export writes, and the Languages to expect."""

    economy: EconomyCode
    # The organizer Coverage Matrix spelling ("Lao PDR", "Viet Nam", "Russian
    # Federation"); this is the value written into the Economy column.
    official_name: str = Field(min_length=1)
    # The UN member-state name, only where it differs from official_name.
    un_name: str | None = None
    # Organizer Language values; the first is this Economy's default.
    languages: list[str] = Field(min_length=1)
    hosts: list[str] = Field(default_factory=list)  # whitelist; Source URL host must be in here
    strategy: str = Field(min_length=1)  # one of STRATEGY_NAMES
    # PERMANENTLY manual: this Portal's own site rules forbid automated
    # collection, so Discovery must never be pointed at it and every Document
    # arrives through "Add document". This is NOT the same statement as
    # `strategy: manual`, which nine Economies carry today only because no
    # Discovery strategy has been wired for them yet and which they will lose.
    manual_only: bool = False
    prepared: bool = False  # the Corpus has actually been fetched and checked
    live_test_pool: bool = False  # one of the nine Economies the organizers may draw
    # The politeness FLOOR for this Portal: the least time Discovery may leave
    # between two requests to the same host. A published robots.txt crawl-delay
    # RAISES it and never lowers it, so this is a promise, not a target.
    min_interval_seconds: float = Field(default=1.0, gt=0)
    # The first date we saw this Portal answer its robots.txt with a server
    # error (5xx), recorded by hand after checking the Portal. RFC 9309 section
    # 2.3.1.4 asks a crawler to assume complete disallow while robots.txt is
    # unavailable, and allows it to treat a Portal that has stayed that way for
    # a reasonable period (the RFC names 30 days) as publishing no rules. This
    # date is what turns that second half from a judgement call into data: with
    # no date recorded, an unreadable robots.txt simply refuses.
    robots_unreachable_since: date | None = None
    # What an unavailable robots.txt means for THIS Portal: 'refuse' (the
    # default, and the rule everywhere it is absent) or 'proceed', an
    # operator's recorded decision that this Portal's 5xx is read as no rules
    # published. It bounds nothing else: the spacing floor, the host
    # whitelist and the published rules all apply exactly as before, and the
    # record of any request made under 'proceed' carries the status the Portal
    # gave and this policy, so nobody has to infer why we went ahead.
    robots_unavailable_policy: str = "refuse"
    # Hosts of this Portal that answer only over plain http from where we
    # run (port 443 closed on the path). A Source URL on one of them may be
    # http://, and its robots.txt is then read over http too; every other
    # host keeps reading robots.txt over https. It is a per-host allowance,
    # never a downgrade for the Economy.
    http_hosts: list[str] = Field(default_factory=list)
    # How long one request of a Discovery by Pillar may take on this
    # Portal's hosts, for a Portal whose answers are slow but whole. Left
    # out, the Discovery's own short timeout applies.
    fetch_timeout_seconds: float | None = Field(default=None, gt=0)
    notes: str | None = None

    @model_validator(mode="after")
    def _whitelist_or_manual(self) -> "PortalConfig":
        if self.strategy not in STRATEGY_NAMES:
            raise ValueError(
                f"{self.economy}: unknown Discovery strategy '{self.strategy}';"
                f" known strategies are {list(STRATEGY_NAMES)}"
            )
        unknown = [lang for lang in self.languages if lang not in ORGANIZER_LANGUAGES]
        if unknown:
            raise ValueError(
                f"{self.economy}: languages not on the organizer's list: {unknown}"
                f" (use 'Other'; the list is {list(ORGANIZER_LANGUAGES)})"
            )
        if not self.hosts and self.strategy != MANUAL_STRATEGY:
            raise ValueError(
                f"{self.economy}: an empty host whitelist is only allowed with"
                f" strategy '{MANUAL_STRATEGY}', not '{self.strategy}'"
            )
        if self.robots_unavailable_policy not in ROBOTS_UNAVAILABLE_POLICIES:
            raise ValueError(
                f"{self.economy}: robots_unavailable_policy"
                f" '{self.robots_unavailable_policy}' is not a policy;"
                f" it is one of {list(ROBOTS_UNAVAILABLE_POLICIES)}, and"
                " leaving the line out means 'refuse'"
            )
        if self.manual_only and self.strategy != MANUAL_STRATEGY:
            raise ValueError(
                f"{self.economy}: manual_only means Discovery must never run"
                f" here, so its strategy must be '{MANUAL_STRATEGY}',"
                f" not '{self.strategy}'"
            )
        stray = [h for h in self.http_hosts if h not in self.hosts]
        if stray:
            raise ValueError(
                f"{self.economy}: http_hosts must be hosts of this Portal;"
                f" {stray} are not in its hosts list"
            )
        return self


# Hosts no lane of ours ever requests, on any path and any rung, whatever a
# baseline row, a Portal answer, an operator or a redirect names: the Thai law
# portal and the Royal Gazette (out of scope by decision), and China's national
# law database, whose robots.txt forbids every crawler. Here, not in crawl.py,
# so the add lane can refuse them without importing the network stack.
NEVER_REQUESTED_HOSTS = frozenset(
    {"law.go.th", "ratchakitcha.soc.go.th", "flk.npc.gov.cn"}
)


def is_never_requested(host: str) -> bool:
    """Is this host, or a domain it sits under, on the never-requested list?
    Any subdomain counts, and a trailing dot or a port changes nothing."""
    h = (host or "").split("@")[-1].split(":")[0].rstrip(".").lower()
    return any(h == d or h.endswith("." + d) for d in NEVER_REQUESTED_HOSTS)


# What an untagged crawl-seed family covers: the Pillars every seed was chosen
# for before seeds carried Pillar tags.
UNTAGGED_SEED_PILLARS = (6, 7)


class CrawlFamily(_Contract):
    """One source family inside an economy's crawl seeds. SG resolves `acts`
    (SSO short codes) to direct act URLs; AU and MY resolve `queries` through
    the portal's own search API. A family must carry at least one seed.

    A family with `urls` is ONE law at fixed official addresses instead: a
    Discovery by Pillar fetches the first address that answers with the law's
    text, for any Economy, with or without a Portal crawler. It serves the
    Indicators it lists (and so their Pillars), and where `baseline_law` names
    a law of the 2025 baseline its addresses are tried first for that law."""

    acts: list[str] = Field(default_factory=list)
    queries: list[str] = Field(default_factory=list)
    # The Pillars this family is likely to carry evidence for. Left out, the
    # family means what every seed meant before Pillars were tagged: 6 and 7.
    pillars: list[int] | None = None
    # Official Source URLs of one law, in the order to try.
    urls: list[str] = Field(default_factory=list)
    # That law's name, which becomes the Document title.
    law: str | None = None
    # The Indicators the law serves.
    indicators: list[str] = Field(default_factory=list)
    # The start of the baseline law name these addresses belong to, if any.
    baseline_law: str | None = None
    # The organizer Language of the text at these addresses, where it is not
    # the Economy's default (an official English translation, say).
    language: str | None = None

    def covers(self, pillar: int) -> bool:
        """Does a Discovery for this Pillar run this family?"""
        if self.urls:
            return any(i.split(".")[0] == str(pillar) for i in self.indicators)
        return pillar in (self.pillars if self.pillars else UNTAGGED_SEED_PILLARS)

    @model_validator(mode="after")
    def _non_empty(self) -> "CrawlFamily":
        if not self.acts and not self.queries and not self.urls:
            raise ValueError("a crawl family needs at least one act code, query or URL")
        if self.urls and (not self.law or not self.indicators):
            raise ValueError("a family of URLs names its law and the Indicators it serves")
        if self.language is not None and self.language not in ORGANIZER_LANGUAGES:
            raise ValueError(
                f"language '{self.language}' is not on the organizer's list"
                f" {list(ORGANIZER_LANGUAGES)}"
            )
        return self


class CrawlSeedsEconomy(_Contract):
    """Per-economy crawl seeding (config/crawl_seeds.yaml): source families and
    the politeness floor. AU's robots.txt asks for a 10s crawl delay."""

    rate_limit_seconds: float = Field(gt=0)
    families: dict[str, CrawlFamily] = Field(min_length=1)
    # How many listing pages one seed may walk. It binds the plans that page
    # through a Portal's own index (Lao PDR) and is ignored by the ones whose
    # search answers in a single call, so the bound on how much of a Portal we
    # ask for is configuration rather than a number buried in an adapter.
    max_pages: int = Field(default=10, ge=1)


class UnknownEngine(ValueError):
    """The caller named an Engine that config/models.yaml does not declare. The
    message always lists the declared names, so a typo is self-correcting."""


ENGINE_NAME_RE = r"^[a-z0-9][a-z0-9-]*$"


# The ceiling on Mapping calls in flight, for the registry, the pipeline, the
# command line and the run endpoint alike. One number, declared where the
# Engine model itself can bound against it, so the three callers cannot drift.
MAX_CONCURRENCY = 32


class Engine(_Contract):
    """One declared Engine: the whole model configuration a run uses, named in
    the UI, on the command line and in the Run Record. Every field is required
    (no defaults) except num_retries, so a half-written registry entry fails at
    load instead of silently inheriting a value nobody chose. num_retries is
    pinned 0 in config and asserted here: silent transport retries corrupt our
    attempt counting (a known LiteLLM/OpenAI SDK trap).

    concurrency is how many Mapping calls one Run may have in flight on THIS
    Engine. It belongs to the Engine rather than to the pipeline because the
    limit is the provider's: a hosted Engine tolerates several at once, a
    locally served one is a single machine and stays at 1, and the fake Engine
    has nothing to gain from a thread pool. It is declared, never defaulted, so
    a new registry entry cannot inherit a rate limit nobody chose for it."""

    name: str  # the registry key, injected by ModelsConfig
    display_name: str
    litellm_model: str  # e.g. "openrouter/qwen/qwen3-30b-a3b-instruct-2507"
    provider: Literal["openrouter", "ollama", "fake"]
    api_key_env: str | None  # env var NAME only; the key itself never leaves .env
    usd_per_million_input_tokens: float = Field(ge=0)
    usd_per_million_output_tokens: float = Field(ge=0)
    open_weights: bool
    structured_output: Literal["json_schema", "ollama_format", "none"]
    concurrency: int = Field(ge=1, le=MAX_CONCURRENCY)
    num_retries: Literal[0] = 0


class Embedder(_Contract):
    """The shared embedding model (M5 gate). Not an Engine: it is never chosen
    by the user and every Engine runs against the same one."""

    name: str
    litellm_model: str  # e.g. "ollama/bge-m3"
    api_key_env: str | None = None
    num_retries: Literal[0] = 0


class ModelsConfig(_Contract):
    """The Engine registry (config/models.yaml): the declared Engines plus the
    shared embedder. The dict key IS the Engine name."""

    default_engine: str
    engines: dict[str, Engine] = Field(min_length=1)
    embedder: Embedder

    @model_validator(mode="before")
    @classmethod
    def _inject_names(cls, data):
        """The yaml key is the name; an entry never restates it (and cannot
        disagree with it)."""
        if not isinstance(data, dict):
            return data
        engines = data.get("engines")
        if not isinstance(engines, dict):
            return data
        out = dict(data)
        out["engines"] = {
            key: ({**entry, "name": key} if isinstance(entry, dict) else entry)
            for key, entry in engines.items()
        }
        return out

    @model_validator(mode="after")
    def _coherent_registry(self) -> "ModelsConfig":
        import re as _re

        for name in self.engines:
            if not _re.match(ENGINE_NAME_RE, name):
                raise ValueError(
                    f"invalid Engine name '{name}': lowercase letters, digits and"
                    " hyphens only, starting with a letter or digit"
                )
        if "embedder" in self.engines:
            raise ValueError("'embedder' is the shared embedder, not an Engine name")
        if self.default_engine not in self.engines:
            raise ValueError(
                f"default_engine '{self.default_engine}' is not a declared Engine:"
                f" expected one of {', '.join(sorted(self.engines))}"
            )
        return self

    @property
    def engine_names(self) -> list[str]:
        return sorted(self.engines)

    def engine(self, name: str) -> Engine:
        """The named Engine, or UnknownEngine listing the valid names."""
        try:
            return self.engines[name]
        except KeyError:
            raise UnknownEngine(
                f"unknown Engine '{name}': expected one of {', '.join(self.engine_names)}"
            ) from None


class RunRecord(_Contract):
    """The saved facts of one Run or one Discovery, as the runs
    table holds them. It is the record of truth: the server's live narration is
    memory, this survives a restart and is the downloadable hand-in.

    documents_fetched is always 0 on a Run (a Run reads the Corpus and never
    fetches); a Discovery carries its own count. cost_usd is computed from the
    Engine's DECLARED per-million prices; provider_cost_usd is the provider's
    own reported figure when it sends one, so the two can be compared against a
    bill instead of trusted. details carries the lane's counters (a Run's
    funnel, a Discovery's strategy and fetch split)."""

    run_id: str
    kind: Literal["run", "discovery"]
    economy: str
    pillars: list[int] = Field(default_factory=list)
    indicators: list[str] | None = None
    engine: str | None = None
    # interrupted: the process that opened this record died before closing it,
    # and the server's next start said so rather than leaving it reading
    # `running` forever.
    status: Literal["running", "completed", "failed", "interrupted"]
    started_at: str
    ended_at: str | None = None
    documents_fetched: int = Field(default=0, ge=0)
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    cost_usd: float = Field(default=0.0, ge=0)
    provider_cost_usd: float | None = None
    error: str | None = None
    details: dict = Field(default_factory=dict)
    # Where the Run's typed events were recorded, relative to the working
    # database's directory (run_events/<run_id>.jsonl), when the app recorded
    # them. Not a column: the server fills it in when the file is there.
    events_file: str | None = None

    @classmethod
    def from_row(cls, row: dict) -> "RunRecord":
        """One runs row (as storage decodes it) as a validated record. JSON
        columns are accepted either decoded or still encoded, so a caller
        reading the table with its own connection needs no decoder."""
        import json as _json

        data = dict(row)
        for key in ("pillars", "indicators", "details"):
            value = data.get(key)
            if isinstance(value, (str, bytes)):
                data[key] = _json.loads(value)
        data["pillars"] = data.get("pillars") or []
        data["details"] = data.get("details") or {}
        return cls(**{k: v for k, v in data.items() if k in cls.model_fields})


class CorpusDoc(_Contract):
    """Document-level export metadata (config/corpus.yaml): the source of the
    submission's Economy / Law Name / Law Number / Last Amended / Source URL
    columns. url_is_direct=False flags a portal-root placeholder that the M10
    crawl must replace with the direct act URL (surfaced in Notes).
    known_matrix_law_name overrides law_name for KNOWN/NEW matching only: set
    it when the ESCAP database cites the law under a different title (e.g. a
    pre-assent Bill name) so the display name can be corrected without
    breaking the provision-level match."""

    economy: EconomyCode
    law_name: str = Field(min_length=1)
    law_number_ref: str | None = None
    last_amended: str | None = None
    source_url: str = Field(pattern=r"^https?://")
    url_is_direct: bool = True
    known_matrix_law_name: str | None = None


class LawMetadata(_Contract):
    """Law Name, Law Number / Ref and Last Amended for a Document that is NOT
    in config/corpus.yaml (config/law_metadata.yaml, keyed by document id). Such
    a Document has no generated corpus entry to carry them, and its own text
    rarely states them in a form the mechanical derivation can read, so a
    person records them from the official text and the file says where.
    law_name replaces the title derived from the Document when the derived one
    is abbreviated or misread."""

    law_name: str | None = Field(default=None, min_length=1)
    law_number_ref: str | None = None
    last_amended: str | None = None


class IndicatorDef(_Contract):
    """One RDTII 2.1 Indicator: the organizer's name plus the working definition
    (M6 prompt input and MappingRecord.indicator_name source), and the sheet
    facts behind it. config/indicators.json, written by
    scripts/make_indicators.py."""

    pillar: int = Field(ge=1, le=12)
    name: str = Field(min_length=1)
    definition: str = Field(min_length=1)
    # false = the Round 1 hand-written text, kept byte for byte; true = composed
    # mechanically from the organizer's sheets, never by a model.
    definition_derived: bool = False
    criteria: str | None = None  # Methodology sheet, verbatim
    score_levels: list[str] = Field(default_factory=list)
    weight: float | None = None  # given only for pillars 6 and 7
    exception: str | None = None
    # false for an Indicator no statute can answer (6.5 is treaty
    # participation): the Gate never shortlists for it.
    legislation_mapped: bool = True


class PillarDef(_Contract):
    """One RDTII 2.1 Pillar: its official name and the Indicators under it.
    config/pillars.json. The pillar DESCRIPTION the Gate embeds lives in
    config/pillar_N_keywords.json, beside the vocabulary that shares its
    provenance."""

    name: str = Field(min_length=1)
    indicator_ids: list[IndicatorId] = Field(min_length=1)


class CrosswalkConfig(_Contract):
    """Indicator ID emission: numeric identity by default; P-codes as the
    documented alternative. Never mixed: one scheme per export run.

    The numeric scheme is GENERATED by load_crosswalk over the loaded Indicator
    registry rather than listed in the file, so a new Indicator needs no config
    edit. A scheme that IS listed (p_code) stays scoped to the Indicators it
    names; load_crosswalk checks that each of them exists."""

    emission_scheme: str = Field(min_length=1)
    schemes: dict[str, dict[str, str]]

    @model_validator(mode="after")
    def _complete(self) -> "CrosswalkConfig":
        if self.emission_scheme not in self.schemes:
            raise ValueError(
                f"emission_scheme '{self.emission_scheme}' not defined in schemes"
                f" {sorted(self.schemes)}"
            )
        for name, mapping in self.schemes.items():
            if not mapping:
                raise ValueError(f"scheme '{name}' is empty")
        return self


class PipelineConfig(_Contract):
    """Mechanical knobs. Defaults encode the hard rules; tests assert them."""

    extraction_attempts: int = Field(default=3, ge=1, le=3)  # 1 initial + 2 stricter retries
    # How long a Discovery by Pillar spends fetching baseline laws before it
    # stops and lists the rest, so the crawler and both Engine passes still fit
    # inside the live hour.
    discovery_baseline_budget_seconds: float = Field(default=600.0, gt=0)
    # The whole of a Discovery by Pillar, both stages together: checked before
    # every request it makes, so a silent Portal cannot eat the hour.
    discovery_drawn_budget_seconds: float = Field(default=900.0, gt=0)
    ocr_trigger_chars_per_page: int = 50
    ocr_cer_max: float = 0.05  # CER gate
    ocr_dpi: int = 300  # pinned rasterization DPI (M2)
    # Escalation gate: Tesseract below EITHER proxy -> RapidOCR lane fires.
    ocr_escalation_min_confidence: float = 0.60
    ocr_escalation_min_dict_hit: float = 0.50
    # After escalation: still below EITHER floor -> manual_review, never silently passed.
    ocr_manual_min_confidence: float = 0.55
    ocr_manual_min_dict_hit: float = 0.40
    confidence_auto_approve: float = 0.90
    confidence_flag_below: float = 0.70
    # Chunking (M4). A run of consecutive increasing section numbers must reach
    # chunk_min_run (per-profile overrides for unambiguous patterns live in
    # chunk.py) and the median detected section must be at least
    # chunk_min_median_chars, else the deterministic splitter declares failure
    # and the LLM boundary fallback fires (offsets and labels only).
    chunk_min_run: int = Field(default=5, ge=2)
    chunk_min_median_chars: int = Field(default=200, ge=0)
    chunk_fallback_attempts: int = Field(default=2, ge=1, le=3)  # 1 initial + 1 stricter retry
    chunk_fallback_max_lines: int = Field(default=4000, ge=1)  # larger docs degrade, no windowing
    # Gate (M5). A chunk survives an indicator iff its pillar cosine clears
    # gate_pillar_cosine_min AND it ranks in the indicator's bm25 top-k with a
    # positive score. Calibrated on the real fixtures.
    gate_pillar_cosine_min: float = Field(default=0.45, ge=0.0, le=1.0)
    gate_bm25_top_k: int = Field(default=20, ge=1)
    # A Document whose letters are more than this share non-Latin takes the
    # meaning-only Gate whatever its Language says, because the bm25 tier's
    # tokenizer and stopword list are English. The same top-k then caps the
    # cosine ranking, so the Engine call budget does not move.
    gate_non_latin_share_max: float = Field(default=0.20, ge=0.0, le=1.0)
    # Translation gloss (M3). A Run over a non-English Document drafts a Gloss
    # for each of its Mappings with the SELECTED Engine and stores it labelled
    # and unreviewed; a Gloss ships without the label only once a named person
    # has approved it (a Reviewed Gloss). Set False to run without the lane.
    gloss_enabled: bool = True
    gloss_engine: Literal["opus_mt", "llm"] = "opus_mt"
    gloss_model_dir: str = "models/opus_mt_mul_en_ct2"  # scripts/fetch_m3_weights.py
    gloss_max_chars: int = Field(default=4000, ge=1)  # per-item input cap
    # A word 3-gram repeating more than this many times marks the output
    # degenerate (the observed opus-mt failure mode on unsupported languages).
    gloss_max_trigram_repeats: int = Field(default=3, ge=1)


# ---------------------------------------------------------------------------
# M3 - translation gloss
# ---------------------------------------------------------------------------

# The mandatory prefix on every AI translation a human might read; export.py
# composes the same label for the shipped Verbatim English column.
GLOSS_LABEL = "[AI translation, non-authoritative]"

# What the Verbatim English column says when drafting produced nothing usable
# (the english=None fallback lane). It carries the label like any other value
# in that column, so the export battery judges it by the one rule it already
# has. Saying nothing is not an option: an empty cell reads as a missing
# translation, which turns the whole Export red over one quote, and a reader
# cannot tell a forgotten rendering from one the model could not produce.
GLOSS_UNAVAILABLE = (
    f"{GLOSS_LABEL} not available: the translation lane produced no usable"
    " English for this quote. The Verbatim Snippet is the only authority."
)


class Gloss(_Contract):
    """One DRAFT English gloss of a non-English source text. NON-AUTHORITATIVE
    by construction: `authority` is the literal "draft", `ai_generated` is the
    literal True, and the model is frozen, so neither validated construction
    nor attribute assignment can mint an approved or human gloss (model_copy
    and model_construct bypass validation, as on every pydantic model; no code
    may use them on a Gloss). The canonical stream and the verbatim columns
    are never touched; a draft ships labelled, and ships unlabelled only after
    a named person approves it (see GlossRecord)."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    key: str = Field(min_length=1)  # mapping_id (review lane) or chunk_id (working lane)
    source_text: str = Field(min_length=1)
    source_language: str = "und"  # script-detected where possible, else "und"
    english: str | None  # None = gloss failure or degenerate output (fallback lane)
    engine: str = Field(min_length=1)  # e.g. "opus-mt-mul-en-ct2" or "llm:<model>"
    authority: Literal["draft"] = "draft"
    ai_generated: Literal[True] = True
    uncertainty_flag: Literal["no-clear-translation-equivalent"] | None = None

    @model_validator(mode="after")
    def _failure_carries_flag(self) -> "Gloss":
        if self.english is None and self.uncertainty_flag is None:
            raise ValueError("a gloss without english text must carry the uncertainty flag")
        return self

    @property
    def labelled_english(self) -> str | None:
        """The only human-facing rendering: label first, always."""
        if self.english is None:
            return None
        return f"{GLOSS_LABEL} {self.english}"


class GlossRecord(_Contract):
    """One Gloss as the working database holds it: the English rendering of the
    Verbatim Quote of ONE Mapping of ONE Run.

    (run_id, mapping_id) identifies it, so a Gloss drafted in Run A can never
    attach to Run B's identically-named Mapping. A Gloss ships with its label
    until `reviewed_by` names the person who approved it: that name is the whole
    difference between a Gloss and a Reviewed Gloss, and the export battery
    checks it mechanically rather than trusting a flag."""

    run_id: str = Field(min_length=1)
    mapping_id: str = Field(min_length=1)
    english: str | None  # None = drafting failure (the uncertainty-flag lane)
    label: str = GLOSS_LABEL
    reviewed: bool = False
    reviewed_by: str | None = None  # the named person; empty is never a review
    reviewed_at: datetime | None = None
    source_language: str = "und"
    engine: str = Field(min_length=1)  # the Engine that drafted it
    uncertainty_flag: str | None = None
    drafted_at: datetime

    @model_validator(mode="after")
    def _reviewed_means_named(self) -> "GlossRecord":
        if self.reviewed and not (self.reviewed_by or "").strip():
            raise ValueError("a Reviewed Gloss must name the person who approved it")
        return self


# --- how a Document's bytes reached the Corpus -----------------------------
#
# One vocabulary, here rather than in the module that writes it, because the
# Export reads these values to decide what a row must disclose and must not
# import the "Add document" lane (and its extraction stack) to learn them.
# regcompass.corpus re-exports all three, so the add lane keeps its own names.

# Found by Discovery at the Economy's official Portal. The default.
DISCOVERY_SOURCE_KIND = "discovery"
# Uploaded, or fetched from a Source URL a reviewer supplied by hand.
MANUAL_SOURCE_KIND = "manual"
# Copied in by `regcompass seed` from the legislation bundled with this
# install: the real Act, but not what the Portal served on the day of the Run.
# A demonstration Corpus, and every row built on it says so.
FIXTURE_SOURCE_KIND = "fixture"


# --- how a manual upload is filed in the fetch manifest --------------------
#
# The manifest's primary key is the URL, which is right for Discovery: a URL
# fetched once is never fetched again, and that is what makes a second Engine's
# pass over the same Corpus cost nothing. It is wrong for an upload. Several
# statutes are published under one landing page, and an assessor pasting that
# page for each of them was filing every upload on ONE manifest row: the second
# file overwrote the first row's bytes while the first Document kept its name,
# so one law's text appeared under another law's title.
#
# So an upload is keyed by its address AND its own digest. The address says
# where the Document is published (and is what reaches the Corpus row's Source
# URL column); the digest says WHICH Document, which is the part the address
# alone could never carry. An upload with no address keeps the older scheme,
# where the digest is the whole key.
#
# These live here, beside the source kinds, because the ingest reads a manifest
# key back into a Source URL and must not import the add lane to learn how.

#: The key an upload with no Source URL is filed under. It never reaches the
#: Corpus row's Source URL column, and never reaches an export.
LOCAL_UPLOAD_SCHEME = "local-upload"

#: What separates an upload's address from its digest inside a manifest key.
UPLOAD_DIGEST_MARKER = "#sha256="

_SHA256_HEX = re.compile(r"\A[0-9a-f]{64}\Z")


def manifest_key_for_upload(source_url: str | None, sha256: str) -> str:
    """The manifest key one uploaded file is filed under.

    With an address: that address plus the digest, so two files an operator
    gave the same address both keep a row of their own. Without one: the digest
    under a scheme nothing will mistake for a Portal address."""
    if not source_url:
        return f"{LOCAL_UPLOAD_SCHEME}:{sha256}"
    return f"{source_url}{UPLOAD_DIGEST_MARKER}{sha256}"


def manifest_address(key: str) -> str | None:
    """Where the Document behind this manifest key is published, or None.

    A Discovery key is already the address. An upload key carries the digest
    beside it and gives back the address alone; an address-less upload gives
    back None, which is the truth about it and what makes the local-copy link
    and the Export's refusal both read correctly."""
    if key.startswith(f"{LOCAL_UPLOAD_SCHEME}:"):
        return None
    address, marker, digest = key.rpartition(UPLOAD_DIGEST_MARKER)
    if marker and address and _SHA256_HEX.match(digest):
        return address
    return key
